// ============================================================
// state.js —— 共享运行时状态（导出对象 S）
// ESM 不能跨模块给 let 重新赋值；各模块 import { S } 后改 S.scene / S.G。
// 禁止把可变游戏状态挂到 globalThis。
// ============================================================

export const S = {
  AC: null,
  SND: true,
  bgmTimer: null,
  bgmStep: 0,
  bgmTrack: null,
  maze: null,
  curMap: 'village',
  G: null,
  scene: 'title',
  storyPage: 0,
  storyLineAt: 0,
  dir: 'D',
  anim: null,
  saveMsg: '',
  curSaveSlot: 1,
  msgTO: null,
  blog: [],
  battleBusy: false,
  battleTurn: 0,
  blogView: 0,
  shopSel: 0,
  pauseSel: 0,
  shopList: [],
  innPrice: 10,
  helpPage: 0,
  codexScroll: 0,
  achScroll: 0,
  travelSel: 0,
  curNpc: null,
  talkPages: [],
  talkPage: 0,
  createName: 0,
  createDiff: 0,
  titleFlash: 0,
  skillMenuOpen: false,
  enemy: null,
  fx: [],
  parr: [],
  walk: null,
  encGauge: 0,
  battleQ: [],
  battleAdvancing: false,
  battleTimer: null,
};
